theme = "kanagawa"

[editor]
line-number="relative"
cursorline=true

[editor.lsp]
display-inlay-hints=true

[editor.soft-wrap]
enable=true

[editor.cursor-shape]
normal="underline"
insert="block"
select="block"

[editor.whitespace]
render="all"

[editor.indent-guides]
render=true
skip-levels=1


[editor.file-picker]
hidden=false
